### ISSUE TITLE
Change size of popup window?

### ISSUE THREAD

**Issue by jschell42** [scholarslab/Neatline#329]
Is there a way to change the size of the popup window that appears when you click on a point/polygon? Thanks!

**Comment by davidmcclure** [comment]
Hey @jschell42,

There's no way to do this via the Neatline editor, but this is really easy to change at the level of the theme. You'll want to hook onto the `.bubble.static` classes. Since the size of the content in the bubble will usually vary quite a bit, depending on how much text / metadata is added to the record, it's probably best to use `max-width` and `max-height`, instead of baking in static dimensions. Eg:

``` css
.bubble.static {
  max-width: 500px;
  max-height: 90%;
}
```

For reference, here are the default styles added by Neatline:

``` css
.bubble.static {
  overflow-y: auto;
  position: absolute;
  background: white;
  border-radius: 2px;
  color: black;
  padding: 1em;
  max-height: 90%;
  max-width: 400px;
  left: 70px;
  top: 20px;
  opacity: 0.85;
}
```

Which are defined in this [stylus file](https://github.com/scholarslab/Neatline/blob/master/views/shared/css/stylus/public/bubble.styl). New CSS could be added either to the Omeka theme, which would change the bubbles in all Neatline exhibits, or to an exhibit-specific theme - see [this post](http://www.scholarslab.org/geospatial-and-temporal/theming-neatline-exhibits/) for details.
