### ISSUE TITLE
Tags in stylesheets get matched when they contain another tag as a substring

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#335]
There appears to be a bug in the regex that pulls out the selectors in the stylesheets. Eg, if you've got:

``` css
.overview {
  stroke-width: 10;
}
```

And also:

``` css
.overview-line {
  fill-color: #ffffff;
}
```

It seems as if the `.overview` selector is also matching `overview-line`.
